# Generated by Django 6.1.1 on 2026-09-24 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmid', models.PositiveIntegerField(help_text='Identifiant unique de la ressource dans Proxmox.', unique=True)),
                ('name', models.CharField(help_text='Nom de la VM ou du conteneur.', max_length=100)),
                ('resource_type', models.CharField(choices=[('VM', 'Machine virtuelle'), ('LXC', 'Conteneur LXC')], max_length=3)),
                ('node', models.CharField(help_text='Nom du nœud Proxmox hébergeant la ressource.', max_length=100)),
                ('cpu_cores', models.PositiveIntegerField(default=1, help_text='Nombre de cœurs CPU configurés.')),
                ('memory_mb', models.PositiveIntegerField(help_text='Mémoire RAM configurée en Mo.')),
                ('disk_gb', models.PositiveIntegerField(default=10, help_text='Taille du disque en Go.')),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('power_state', models.CharField(choices=[('running', 'En fonctionnement'), ('stopped', 'Arrêtée'), ('unknown', 'Inconnu')], default='unknown', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
