# Generated by Django 6.1.1 on 2026-09-24 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du réseau logique.', max_length=100, unique=True)),
                ('network_type', models.CharField(choices=[('bridge', 'Bridge'), ('vlan', 'VLAN')], default='bridge', max_length=20)),
                ('bridge_name', models.CharField(help_text='Nom du bridge Open vSwitch.', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_vmid', models.PositiveIntegerField(help_text='Identifiant VM/LXC dans Proxmox.')),
                ('interface_name', models.CharField(help_text="Nom de l'interface réseau, par exemple eth0.", max_length=50)),
                ('interface_type', models.CharField(choices=[('virtio', 'VirtIO'), ('e1000', 'Intel E1000'), ('other', 'Autre')], default='virtio', max_length=20)),
                ('mac_address', models.CharField(blank=True, max_length=17)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('vlan_id', models.PositiveIntegerField(blank=True, help_text='VLAN associé à cette interface, si applicable.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='network.network')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('resource_vmid', 'interface_name'), name='unique_interface_per_resource')],
            },
        ),
        migrations.CreateModel(
            name='VLAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.PositiveIntegerField(help_text='Identifiant du VLAN (1 à 4094).')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='network.network')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('network', 'vlan_id'), name='unique_vlan_per_network')],
            },
        ),
    ]
