# Generated by Django 6.1.1 on 2026-09-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nom de la règle d'alerte.", max_length=100, unique=True)),
                ('metric', models.CharField(help_text='Métrique surveillée, par exemple CPU ou mémoire.', max_length=100)),
                ('condition', models.CharField(help_text="Condition de déclenchement de l'alerte.", max_length=255)),
                ('threshold', models.FloatField(help_text='Seuil de déclenchement.')),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critical', 'Critique')], default='warning', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la cible de supervision.', max_length=100, unique=True)),
                ('target_type', models.CharField(choices=[('proxmox', 'Proxmox VE'), ('vm', 'Machine virtuelle'), ('lxc', 'Conteneur LXC'), ('docker', 'Conteneur Docker'), ('network', 'Réseau')], max_length=20)),
                ('endpoint', models.CharField(blank=True, help_text='Adresse ou endpoint utilisé pour la supervision.', max_length=255)),
                ('prometheus_job', models.CharField(blank=True, help_text='Nom du job Prometheus associé.', max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('firing', 'Déclenchée'), ('resolved', 'Résolue')], max_length=20)),
                ('value', models.FloatField(blank=True, help_text='Valeur de la métrique au moment du déclenchement.', null=True)),
                ('message', models.TextField(blank=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='monitoring.alertrule')),
            ],
        ),
        migrations.AddField(
            model_name='alertrule',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='monitoring.monitoringtarget'),
        ),
    ]
