# Generated by Django 6.1.1 on 2026-09-24 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WireGuardTunnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du tunnel WireGuard.', max_length=100, unique=True)),
                ('interface_name', models.CharField(default='wg0', help_text="Nom de l'interface WireGuard.", max_length=50, unique=True)),
                ('address', models.GenericIPAddressField(help_text='Adresse IPv4 du tunnel WireGuard.')),
                ('listen_port', models.PositiveIntegerField(default=51820, help_text="Port d'écoute UDP de WireGuard.")),
                ('network', models.CharField(help_text='Réseau VPN, par exemple 10.8.0.0/24.', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WireGuardPeer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du pair WireGuard.', max_length=100)),
                ('public_key', models.CharField(help_text='Clé publique du pair.', max_length=64, unique=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='Adresses ou réseaux autorisés pour ce pair.')),
                ('endpoint', models.CharField(blank=True, help_text='Adresse endpoint du pair, si nécessaire.', max_length=255)),
                ('persistent_keepalive', models.PositiveIntegerField(default=25, help_text='Intervalle Keepalive en secondes.')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peers', to='vpn.wireguardtunnel')),
            ],
        ),
    ]
