# Generated by Django 6.1.1 on 2026-09-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_id', models.CharField(help_text='Identifiant unique du conteneur Docker.', max_length=64, unique=True)),
                ('name', models.CharField(help_text='Nom du conteneur Docker.', max_length=100)),
                ('image', models.CharField(help_text='Image Docker utilisée par le conteneur.', max_length=255)),
                ('status', models.CharField(choices=[('running', 'En fonctionnement'), ('stopped', 'Arrêté'), ('paused', 'En pause'), ('restarting', 'Redémarrage'), ('exited', 'Terminé'), ('created', 'Créé'), ('unknown', 'Inconnu')], default='unknown', max_length=20)),
                ('ports', models.JSONField(blank=True, default=dict, help_text='Mapping des ports exposés par le conteneur.')),
                ('environment', models.JSONField(blank=True, default=dict, help_text="Variables d'environnement du conteneur.")),
                ('restart_policy', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
